[package]
name = "wm-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true
reqwest.workspace = true
bollard.workspace = true
serde.workspace = true
serde_json.workspace = true