[package]
name = "wm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
time.workspace = true
utoipa.workspace = true
thiserror.workspace = true