# Example local defaults (override via env):
# WM_BIND_ADDR, DATABASE_URL, WM_WOLF_SOCK_PATH, WM_DOCKER_SOCK_PATH
bind_addr = "0.0.0.0:8080"
db_url = "sqlite://wm.db"
wolf_sock_path = "/var/run/wolf.sock"
docker_sock_path = "/var/run/docker.sock"